val _ = map (fn thy => (open_theory thy;
	mapfilter delete_thm (flat (map fst (get_thms thy)))))
	(get_descendants "calc_prelims");
open_theory"calc_prelims";
set_pc"cn1";
push_pc"z_library1";
set_goal([], Òµm : NATURAL∑ m æ 0Æ);
a(rewrite_tac[z_get_specÒNATURALÆ] THEN REPEAT strip_tac);
val natural_thm = pop_thm();
pop_pc();
push_pc"z_library1";
set_goal([], Òfact 0 = 1 ± fact 1 = 1Æ);
a(rewrite_tac[cn_fact_thm, rewrite_rule[cn_fact_thm]
	((z_µ_elimÒ0Æ o ±_right_elim) cn_fact_thm)]);
val fact_thm  = pop_thm();
pop_pc();
push_pc"z_library1";
set_goal([], Òµx: ˙∑  x ** 1 = xÆ);
a(REPEAT strip_tac);
a(rewrite_tac[rewrite_rule[](
    z_µ_elimÒ(x ¶ x, y ¶ 0)Æ (±_right_elim(z_get_specÒ(_**_)Æ)))]);
val star_star_1_thm = pop_thm();
set_goal([], Òµx: ˙∑  x ** 2 = x * xÆ);
a(REPEAT strip_tac);
a(rewrite_tac[star_star_1_thm, rewrite_rule[](
    z_µ_elimÒ(x ¶ x, y ¶ 1)Æ (±_right_elim(z_get_specÒ(_**_)Æ)))]);
val star_star_2_thm = pop_thm();
pop_pc();
open_theory "OPS'body";
set_goal([],get_conjecture"-""vcOPS_1");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPS_1";
set_goal([],get_conjecture"-""vcOPS_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPS_2";
set_goal([],get_conjecture"-""vcOPS_3");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPS_3";
set_goal([],get_conjecture"-""vcOPS_4");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPS_4";
open_theory "OPSoDIGIT_BUTTON'proc";
set_goal([],get_conjecture"-""vcOPSoDIGIT_BUTTON_1");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPSoDIGIT_BUTTON_1";
set_goal([],get_conjecture"-""vcOPSoDIGIT_BUTTON_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPSoDIGIT_BUTTON_2";
set_goal([],get_conjecture"-""vc3001_1");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN asm_rewrite_tac[cn_DO_DIGIT_thm]);
save_pop_thm"vc3001_1";
set_goal([],get_conjecture"-""vc3001_2");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN asm_rewrite_tac[cn_DO_DIGIT_thm]);
save_pop_thm"vc3001_2";
open_theory "OPSoOPERATION_BUTTON'proc";
set_goal([],get_conjecture"-""vcOPSoOPERATION_BUTTON_1");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPSoOPERATION_BUTTON_1";
set_goal([],get_conjecture"-""vcOPSoOPERATION_BUTTON_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPSoOPERATION_BUTTON_2";
set_goal([], get_conjecture"-""vc3002_1");
a(cn_vc_simp_tac calc_thms);
a ¥_tac;
a(asm_rewrite_tac[]);
save_pop_thm"vc3002_1";
val number_ax = get_axiom"-""Constraint 1";
set_goal([], get_conjecture"-""vc3002_2");
a(cn_vc_simp_tac calc_thms);
a ¥_tac;
a(asm_rewrite_tac[]);
a(LIST_DROP_NTH_ASM_T[1,2,3,4,5,6,8,9,10] (MAP_EVERY discard_tac));
a strip_tac;
a(lemma_tac ÒGVoDISPLAY ç NATURALÆ);
(* *** Goal "1" *** *)
a(ante_tac number_ax);
a(PC_T1"calc_prelims"asm_rewrite_tac[z_get_specÒNATURALÆ]);
a(DROP_NTH_ASM_T 2 ante_tac THEN PC_T1 "z_lin_arith" prove_tac[]);
(* *** Goal "2" *** *)
a(ALL_FC_T rewrite_tac[z_get_specÒFACTÆ]);
save_pop_thm"vc3002_2";
set_goal([], get_conjecture"-""vc3002_3");
a(cn_vc_simp_tac calc_thms);
a ¥_tac;
a(asm_rewrite_tac[]);
a(LIST_DROP_NTH_ASM_T[1,2,3,4,5,6,7,9,10,11] (MAP_EVERY discard_tac));
a strip_tac;
a(lemma_tac ÒGVoDISPLAY ç NATURALÆ);
(* *** Goal "1" *** *)
a(ante_tac number_ax);
a(PC_T1"calc_prelims"asm_rewrite_tac[z_get_specÒNATURALÆ]);
a(DROP_NTH_ASM_T 2 ante_tac THEN PC_T1 "z_lin_arith" prove_tac[]);
(* *** Goal "2" *** *)
a(ALL_FC_T rewrite_tac[z_get_specÒSQRTÆ]);
save_pop_thm"vc3002_3";
set_goal([], get_conjecture"-""vc3002_4");
a(PC_T1"calc_prelims"cn_vc_simp_tac[]);
a(¥_tac THEN asm_rewrite_tac[]);
save_pop_thm"vc3002_4";
set_goal([], get_conjecture"-""vc3002_5");
a(PC_T1"calc_prelims"cn_vc_simp_tac[]);
a(¥_tac THEN asm_rewrite_tac[]);
save_pop_thm"vc3002_5";
set_goal([], get_conjecture"-""vc3002_6");
a(PC_T1"calc_prelims"cn_vc_simp_tac[]);
a(¥_tac THEN asm_rewrite_tac[]);
save_pop_thm"vc3002_6";
set_goal([], get_conjecture"-""vc3002_7");
a(PC_T1"calc_prelims"cn_vc_simp_tac[]);
a(¥_tac THEN asm_rewrite_tac[]);
save_pop_thm"vc3002_7";
set_goal([], get_conjecture"-""vc3002_8");
a(PC_T1"calc_prelims"cn_vc_simp_tac[]);
a(¥_tac THEN asm_rewrite_tac[]);
save_pop_thm"vc3002_8";
open_theory "OPSoOPERATION_BUTTONoFACT'func";
set_goal([],get_conjecture"-""vcOPSoOPERATION_BUTTONoFACT_1");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN all_fc_tac[natural_thm]);
save_pop_thm"vcOPSoOPERATION_BUTTONoFACT_1";
set_goal([],get_conjecture"-""vcOPSoOPERATION_BUTTONoFACT_2");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac);
a(all_var_elim_asm_tac1);
save_pop_thm"vcOPSoOPERATION_BUTTONoFACT_2";
set_goal([],get_conjecture"-""vc1001_1");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN asm_rewrite_tac[fact_thm]);
save_pop_thm"vc1001_1";
set_goal([],get_conjecture"-""vc1001_2");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac);
a(lemma_tacÒM = 0 ≤ M = 1Æ
	THEN1 PC_T1"z_lin_arith"asm_prove_tac[]
	THEN asm_rewrite_tac[fact_thm]);
save_pop_thm"vc1001_2";
set_goal([],get_conjecture"-""vc1001_3");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac);
a(asm_ante_tacÒ2 º JÆ THEN PC_T1 "z_lin_arith" prove_tac[]);
save_pop_thm"vc1001_3";
set_goal([],get_conjecture"-""vc1001_4");
a(cn_vc_simp_tac[]);
save_pop_thm"vc1001_4";
set_goal([], get_conjecture"-""vc1002_1");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN all_var_elim_asm_tac1);
a(lemma_tacÒ∂K:É∑ K + 1 = JÆ);
(* *** Goal "1" *** *)
a(z_∂_tacÒJ - 1Æ THEN PC_T1 "z_lin_arith" prove_tac[]);
(* *** Goal "2" *** *)
a(all_var_elim_asm_tac1);
a(rewrite_tac[z_plus_assoc_thm]);
a(ALL_FC_T rewrite_tac[cn_fact_thm]);
save_pop_thm "vc1002_1";
open_theory "OPSoOPERATION_BUTTONoSQRT'func";
set_goal([],get_conjecture"-""vcOPSoOPERATION_BUTTONoSQRT_1");
a(cn_vc_simp_tac[]);
save_pop_thm"vcOPSoOPERATION_BUTTONoSQRT_1";
set_goal([],get_conjecture"-""vcOPSoOPERATION_BUTTONoSQRT_2");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN all_var_elim_asm_tac1);
save_pop_thm"vcOPSoOPERATION_BUTTONoSQRT_2";
set_goal([],get_conjecture"-""vc2001_1");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2001_1";
set_goal([],get_conjecture"-""vc2001_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2001_2";
set_goal([], get_conjecture"-""vc2002_1");
a(cn_vc_simp_tac[]);
a(REPEAT ¥_tac THEN all_var_elim_asm_tac1);
a(POP_ASM_T discard_tac THEN all_fc_tac[natural_thm]);
a(DROP_NTH_ASM_T 2 discard_tac);
a(asm_rewrite_tac[star_star_2_thm]);
a(z_º_induction_tacÒMÆ);
(* *** Goal "1" *** *)
a(rewrite_tac[]);
(* *** Goal "2" *** *)
a(PC_T1 "z_lin_arith" asm_prove_tac[]);
save_pop_thm "vc2002_1";
set_goal([],get_conjecture"-""vc2002_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2002_2";
set_goal([],get_conjecture"-""vc2002_3");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2002_3";
set_goal([],get_conjecture"-""vc2003_1");
a(cn_vc_simp_tac[]);
a(REPEAT strip_tac THEN all_var_elim_asm_tac1);
save_pop_thm"vc2003_1";
set_goal([],get_conjecture"-""vc2003_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2003_2";
set_goal([],get_conjecture"-""vc2003_3");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2003_3";
set_goal([],get_conjecture"-""vc2004_1");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2004_1";
set_goal([],get_conjecture"-""vc2004_2");
a(cn_vc_simp_tac[]);
save_pop_thm"vc2004_2";



